version: '2'

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    command: 
      -H unix:///var/run/docker.sock
      --ssl
      --sslcert /portainer.crt
      --sslkey /portainer.key
    restart: always
    ports:
      - 9443:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/portainer:/data
      - ./portainer.key:/portainer.key
      - ./portainer.crt:/portainer.crt
